# Site settings
title: Tennis & Tequila Social Club Atlanta | Social Tennis for Young Professionals
email: info@tennisandtequila.social
description: "Atlanta's social tennis club for young professionals. Join 340+ members for mixers, clinics, and events. No experience required. Serve. Sip. Socialize."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tennisandtequila.social" # the base hostname & protocol for your site

instagram_username: 10sandtequila
slack_link: https://tinyurl.com/32yhwkjh

# Build settings
markdown: kramdown
